#!/usr/bin/env python3.11
"""Vendor the Sacred Press icon family from official Phosphor source.

The product may not take a runtime icon dependency, so the icons it needs are
pulled once from `phosphor-icons/core`, normalised, and written into one closed
local registry that `src/views/components/ui/icon.ejs` renders from.

**Weight.** Phosphor's *regular* weight is drawn at a 1.5px stroke on a 24px
grid — that is the family's own published specification, expressed in the source
as filled outlines on a 256 unit grid (16/256 = 1.5/24). Vendoring regular and
scaling it into a 24 viewBox therefore gives exactly the 24px/1.5px contract the
design calls for, with the weight guaranteed by construction rather than by a
`stroke-width` attribute that any one icon could contradict.

**Closed.** Only the names listed below are vendored, and the registry has no
fallback shape: asking for a name that is not here is a template error, not a
silently rendered circle.

Run from `Node/app`:

    python3.11 scripts/vendor-phosphor-icons.py
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
import urllib.request
from pathlib import Path

APP_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = APP_ROOT / "src" / "views" / "components" / "ui" / "icon-registry.json"
LICENCE_PATH = APP_ROOT / "src" / "views" / "components" / "ui" / "PHOSPHOR-LICENSE.txt"

PHOSPHOR_RAW = "https://raw.githubusercontent.com/phosphor-icons/core/main"

# Every icon the interface actually renders, grouped by the job it does. An
# entry here is a commitment that some real control or state uses it; nothing is
# vendored "in case".
ICONS = {
    # Daily practice — one mark per module on Today, so the three can be told
    # apart while scrolling.
    "shield": "shield",
    "book": "book-open",
    "tasks": "check-square",
    "clock": "clock-countdown",
    # Forms and their states
    "key": "key",
    "lock": "lock",
    "globe": "globe",
    "send": "paper-plane-tilt",
    "warning": "warning",
    "arrow-right": "arrow-right",
    # State. In a monochrome system a failure cannot be marked by a red field,
    # so it is marked by a shape — from this same family, never a second pack.
    # A *selected* control's check is drawn in CSS instead, because the state
    # lives in `aria-pressed` and a mark in the markup would be a second source
    # of truth for it.
    "warning-circle": "warning-circle",
    # Profile and account
    "user": "user",
    "plus": "plus",
    "minus": "minus",
    # Progress
    "flame": "flame",
    "trophy": "trophy",
    # Shared interface furniture
    "more-horizontal": "dots-three",
    "chevron": "caret-down",
    "close": "x",
}

SOURCE_GRID = 256
TARGET_GRID = 24


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "achimari-icon-vendor"})
    with urllib.request.urlopen(request, timeout=60) as response:  # noqa: S310
        return response.read()


def extract(svg: str, upstream: str) -> str:
    """Pulls the drawing out of an upstream Phosphor file, after checking it."""
    view_box = re.search(r'viewBox="([^"]+)"', svg)
    if not view_box or view_box.group(1) != f"0 0 {SOURCE_GRID} {SOURCE_GRID}":
        raise SystemExit(f"{upstream}: unexpected viewBox {view_box and view_box.group(1)}")
    if 'fill="currentColor"' not in svg:
        raise SystemExit(f"{upstream}: upstream no longer draws in currentColor")

    body = svg[svg.index(">", svg.index("<svg")) + 1 : svg.rindex("</svg>")].strip()
    if not body.startswith("<path") or "stroke" in body:
        raise SystemExit(f"{upstream}: expected filled outline paths, got {body[:60]}")
    return body


def main() -> int:
    scale = TARGET_GRID / SOURCE_GRID
    registry = {}
    digests = []

    for name, upstream in sorted(ICONS.items()):
        payload = fetch(f"{PHOSPHOR_RAW}/assets/regular/{upstream}.svg")
        svg = payload.decode("utf-8")
        registry[name] = {"from": upstream, "d": extract(svg, upstream)}
        digests.append((upstream, hashlib.sha256(payload).hexdigest()))
        print(f"  {name:<16} <- phosphor/regular/{upstream}.svg")

    document = {
        "_comment": (
            "Generated by scripts/vendor-phosphor-icons.py from phosphor-icons/core "
            "assets/regular (MIT). Do not edit by hand. Phosphor regular is a 1.5px "
            f"stroke on a 24px grid, drawn on a {SOURCE_GRID} unit grid upstream; the "
            f"renderer scales by {scale} so every icon shares one 0 0 {TARGET_GRID} "
            f"{TARGET_GRID} viewBox and one weight."
        ),
        "sourceGrid": SOURCE_GRID,
        "targetGrid": TARGET_GRID,
        "scale": scale,
        "weight": "regular",
        "icons": registry,
    }
    REGISTRY_PATH.write_text(json.dumps(document, indent=2, sort_keys=False) + "\n")
    print(f"\n  {REGISTRY_PATH.relative_to(APP_ROOT)}  {len(registry)} icons")

    licence = fetch(f"{PHOSPHOR_RAW}/LICENSE").decode("utf-8")
    if "MIT License" not in licence:
        raise SystemExit("upstream licence is no longer MIT; stop and re-check before shipping")
    LICENCE_PATH.write_text(licence)
    print(f"  {LICENCE_PATH.relative_to(APP_ROOT)}  MIT, retained verbatim")
    return 0


if __name__ == "__main__":
    sys.exit(main())
